from colorstorage import ColorStorage

cs = ColorStorage()
cs.encode("""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel porttitor ligula. Ut sollicitudin bibendum mi, vel luctus quam euismod in. Morbi vel nunc magna. Donec quam sapien, interdum convallis dapibus sit amet, placerat a velit. Sed quis massa luctus, pellentesque magna luctus, cursus libero. Ut ullamcorper scelerisque quam. Vestibulum erat purus, blandit eget euismod sit amet, egestas sit amet velit.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec pulvinar lobortis orci nec gravida. Praesent consequat pharetra mauris et suscipit. Aliquam et enim lectus. Ut et mi ex. Integer vel imperdiet orci. Nulla facilisi. In accumsan sodales turpis, eget laoreet odio porta eget. Proin suscipit nec velit tempus dignissim. Fusce ornare mauris sit amet nibh finibus mattis. Nullam imperdiet nunc a erat aliquam, a sollicitudin tellus molestie. Fusce ultrices porttitor elit, elementum scelerisque neque accumsan non. Etiam eu justo in turpis aliquet venenatis. Suspendisse porttitor ligula et ullamcorper tristique. Proin ullamcorper justo ac sapien fermentum, pulvinar malesuada metus gravida. Integer a efficitur risus, et egestas risus.

Proin felis leo, interdum a dolor sit amet, luctus tincidunt ex. Suspendisse tincidunt, metus id condimentum dictum, justo dolor sollicitudin est, non viverra odio enim cursus massa. Phasellus at iaculis tellus. Proin vel vestibulum nibh. Praesent porttitor, urna in suscipit feugiat, lorem est hendrerit lectus, scelerisque hendrerit nisi sapien ornare nibh. Aliquam porta enim non massa rutrum laoreet eget a erat. Nullam eu elit vitae nunc suscipit condimentum. Fusce nec facilisis odio. Morbi mattis bibendum condimentum. Integer semper odio sed est hendrerit sagittis. Maecenas consectetur tempus iaculis. Ut a facilisis risus.

Nam scelerisque tristique arcu ut ullamcorper. Nunc at mi magna. Nulla facilisi. Aliquam erat volutpat. Mauris tristique, odio vitae euismod sagittis, elit sapien auctor massa, eget venenatis lectus nisl et diam. Sed facilisis massa nec eleifend mollis. Donec vel dolor a velit lacinia mollis. Vivamus a tellus consectetur, viverra orci nec, mattis magna. Suspendisse convallis lectus eu sollicitudin porta. Suspendisse ut venenatis mauris. Sed sodales ornare massa. Donec bibendum est lectus, sit amet blandit enim lacinia vel. Suspendisse a mi quis massa fermentum ultricies quis sed sem.

Cras id vestibulum justo. Sed ultricies eu ante et imperdiet. Ut lorem turpis, convallis at condimentum quis, iaculis vitae risus. Maecenas sollicitudin lectus vitae leo feugiat, a semper nisl rhoncus. Nunc tempus, velit ut bibendum euismod, ligula arcu molestie mauris, tristique ultricies tortor urna vitae enim. Suspendisse potenti. Mauris commodo turpis augue, id sodales ligula porta vitae. Ut ultrices pharetra iaculis. Sed ut metus nisi. Nam ultrices nunc non ligula vestibulum, ac cursus purus facilisis. Ut sollicitudin, est eget varius venenatis, eros justo molestie justo, quis molestie diam lacus quis felis. Mauris lobortis in erat in venenatis. Cras fringilla luctus elementum.""", 'image.png')
cs.decode('image.png')
